import type { EngineModule } from './types';

export const ENGINE_MODULES: EngineModule[] = [
  {
    id: 'wgs',
    title: 'Bacterial WGS Decision Engine',
    tagline: 'From pure culture to publication-ready genome — every decision, explained.',
    cat: 'GENOMICS',
    badge: 'Complete',
    status: 'live',
    totalSteps: 11,
    tags: ['WGS', 'Assembly', 'Annotation', 'Taxonomy', 'BGC'],
  },
  {
    id: 'sequencing-advisor',
    title: 'Sequencing Strategy Advisor',
    tagline: 'Find the right sequencing approach for your organism, budget, and research goal.',
    cat: 'SEQUENCING',
    badge: 'Complete',
    status: 'live',
    totalSteps: 8,
    tags: ['16S', 'WGS', 'Metagenomics', 'Hybrid', 'Amplicon'],
  },
  {
    id: 'reference-genome',
    title: 'Reference Genome Selection Assistant',
    tagline: 'Know when to map and when to assemble de novo — with confidence scores.',
    cat: 'ASSEMBLY',
    badge: 'Complete',
    status: 'live',
    totalSteps: 7,
    tags: ['ANI', 'Reference', 'De novo', 'GTDB'],
  },
  {
    id: 'assembly-strategy',
    title: 'Genome Assembly Strategy Selector',
    tagline: 'Illumina, Nanopore, PacBio, or hybrid — pick the right assembler with rationale.',
    cat: 'ASSEMBLY',
    badge: 'Complete',
    status: 'live',
    totalSteps: 6,
    tags: ['SPAdes', 'Flye', 'Unicycler', 'HiFi', 'Hybrid'],
  },
  {
    id: 'mag-recovery',
    title: 'MAG Recovery Decision Tree',
    tagline: 'Guide your metagenome binning pipeline from raw reads to quality MAGs.',
    cat: 'METAGENOMICS',
    badge: 'Complete',
    status: 'live',
    totalSteps: 9,
    tags: ['MAG', 'Binning', 'MetaSPAdes', 'CheckM', 'GTDB-Tk'],
  },
  {
    id: 'functional-prediction',
    title: 'Functional Prediction Wizard',
    tagline: 'Check your QIIME2 and PICRUSt2 readiness — and fix what\'s missing.',
    cat: 'FUNCTIONAL',
    badge: 'Complete',
    status: 'live',
    totalSteps: 7,
    tags: ['QIIME2', 'PICRUSt2', '16S', 'Functional', 'Microbiome'],
  },
  {
    id: 'diff-abundance',
    title: 'Differential Abundance Method Selector',
    tagline: 'DESeq2, ANCOM-BC, ALDEx2 or LEfSe — choose correctly for your data type.',
    cat: 'STATISTICS',
    badge: 'Complete',
    status: 'live',
    totalSteps: 6,
    tags: ['DESeq2', 'ANCOM-BC', 'ALDEx2', 'Statistics', 'Microbiome'],
  },
  {
    id: 'genome-mining',
    title: 'Genome Mining Wizard',
    tagline: 'From genome to validated natural product — a step-by-step discovery pipeline.',
    cat: 'DRUG DISCOVERY',
    badge: 'Complete',
    status: 'live',
    totalSteps: 8,
    tags: ['BGC', 'antiSMASH', 'NRPS', 'PKS', 'AMP', 'RiPP'],
  },
  {
    id: 'pub-readiness',
    title: 'Publication Readiness Checker',
    tagline: 'Score your project against journal standards before you submit.',
    cat: 'PUBLICATION',
    badge: 'Complete',
    status: 'live',
    totalSteps: 5,
    tags: ['QC', 'CheckM', 'BUSCO', 'N50', 'NCBI', 'Checklist'],
  },
  {
    id: 'method-recommender',
    title: 'Bioinformatics Method Recommender',
    tagline: 'Describe your research question — get a ranked analysis roadmap.',
    cat: 'STRATEGY',
    badge: 'Complete',
    status: 'live',
    totalSteps: 5,
    tags: ['AI Advisor', 'Metagenomics', 'Drug Discovery', 'AlphaFold'],
  },
  {
    id: 'experimental-design',
    title: 'Experimental Design Advisor',
    tagline: 'Plan sample sizes, controls, replicates, and sequencing depth before fieldwork.',
    cat: 'PLANNING',
    badge: 'Complete',
    status: 'live',
    totalSteps: 7,
    tags: ['Sample Size', 'Controls', 'Replicates', 'Power', 'Cost'],
  },
  {
    id: 'phd-planner',
    title: 'PhD Project Planner',
    tagline: 'Build an interactive research timeline aligned to your degree and area.',
    cat: 'CAREER',
    badge: 'Complete',
    status: 'live',
    totalSteps: 5,
    tags: ['PhD', 'Timeline', 'Milestones', 'Publications', 'Thesis'],
  },
  {
    id: 'conference',
    title: 'Conference Recommender',
    tagline: 'Find the conferences that matter most for your research keywords.',
    cat: 'CAREER',
    badge: 'Complete',
    status: 'live',
    totalSteps: 4,
    tags: ['ISMB', 'ISME', 'RECOMB', 'Conferences', 'Networking'],
  },
  {
    id: 'career-pathway',
    title: 'Bioinformatics Career Pathway Explorer',
    tagline: 'Map your skill gaps and build a roadmap from where you are to where you want to be.',
    cat: 'CAREER',
    badge: 'Complete',
    status: 'live',
    totalSteps: 6,
    tags: ['Career', 'Skills', 'Academia', 'Industry', 'Roadmap'],
  },
  // ── Modules 15–21 ─────────────────────────────────────────
  {
    id: 'ont-basecalling',
    title: 'ONT Basecalling & Filtering Advisor',
    tagline: 'Dorado models, chemistry pairing, and the Q-score thresholds that actually matter.',
    cat: 'NANOPORE',
    badge: 'Complete',
    status: 'live',
    totalSteps: 7,
    tags: ['Nanopore', 'Dorado', 'Duplex', 'Basecalling', 'Filtlong'],
  },
  {
    id: 'metadata-compliance',
    title: 'Metadata & MIMARKS Compliance Checker',
    tagline: 'Prevent NCBI and ENA rejections before they happen.',
    cat: 'SUBMISSION',
    badge: 'Complete',
    status: 'live',
    totalSteps: 5,
    tags: ['NCBI', 'ENA', 'MIxS', 'ENVO', 'Metadata'],
  },
  {
    id: 'statistical-power',
    title: 'Statistical Power Calculator',
    tagline: 'Plan sample sizes before fieldwork to avoid underpowered microbiome studies.',
    cat: 'STATISTICS',
    badge: 'Complete',
    status: 'live',
    totalSteps: 6,
    tags: ['Power', 'Sample Size', 'PERMANOVA', 'Effect Size', 'FDR'],
  },
  {
    id: 'amp-discovery',
    title: 'AMP / Peptide Discovery Pipeline Wizard',
    tagline: 'From genome to validated antimicrobial peptide — mining, filtering, and wet-lab proof.',
    cat: 'DRUG DISCOVERY',
    badge: 'Complete',
    status: 'live',
    totalSteps: 8,
    tags: ['AMP', 'RiPP', 'antiSMASH', 'Haemolysis', 'MIC'],
  },
  {
    id: 'novel-species',
    title: 'dDDH & Novel Species Description Checklist',
    tagline: 'ANI, dDDH, chemotaxonomy and deposition — the full IJSEM compliance path.',
    cat: 'TAXONOMY',
    badge: 'Complete',
    status: 'live',
    totalSteps: 7,
    tags: ['dDDH', 'TYGS', 'IJSEM', 'SeqCode', 'LPSN'],
  },
  {
    id: 'compute-estimator',
    title: 'Computational Resource Estimator',
    tagline: 'Will this job fit your allocation? RAM, cores, wall-clock and disk, per tool.',
    cat: 'COMPUTING',
    badge: 'Complete',
    status: 'live',
    totalSteps: 6,
    tags: ['HPC', 'SLURM', 'Memory', 'Storage', 'Array Jobs'],
  },
  {
    id: 'primer-selection',
    title: '16S Primer Selection Advisor',
    tagline: 'V3–V4 vs V4 vs full-length — with off-target and coverage bias warnings.',
    cat: 'AMPLICON',
    badge: 'Complete',
    status: 'live',
    totalSteps: 6,
    tags: ['16S', 'Primers', 'V3-V4', 'Chloroplast', 'SILVA'],
  },
];
